esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platform: ESP32
  board: esp32dev
  libraries:
    - "ESP32 BLE Arduino"  # Add this to include the ESP32 BLE Arduino library

# Add other necessary configurations here
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:
   reboot_timeout: 0s

ota:
- platform: esphome

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

external_components:
  - source: github://Nuchaz/esphome_excercise_component

sensor:
  - platform: exercise_sensor
    speed:
      name: "Bike Speed"
      unit_of_measurement: "mph"
    cadence:
      name: "Bike Cadence"
      unit_of_measurement: "rpm"
    power:
      name: "Bike Power"
    distance:
      name: "Session Distance"
      unit_of_measurement: "miles"
    heart:
      name: "Heartrate"
      unit_of_measurement: "bpm"
    workout_time:
      name: "Workout Time"
      unit_of_measurement: "minutes"
    calories:
      name: "Calories Burned"
      unit_of_measurement: "K"

globals:
  - id: user_weight
    type: int
    restore_value: no
    initial_value: '100' # user weight in KG
  - id: user_age
    type: int
    restore_value: no
    initial_value: '40' # user age in years
  - id: user_sex
    type: int
    restore_value: no
    initial_value: '0' # 0 for male, 1 for female.
